# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LYReactNative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LYReactNative
  pod 'LYReactNative' , :path => '../'

  target 'LYReactNativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LYReactNativeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
